### PR TITLE
use /usr/bin/perl

### PR DESCRIPTION
**Pull request by plicease**
Use a consistent shebang line for all scripts.

### CODE REVIEW

**Comment by awwaiid** [comment]
How about `/usr/bin/env perl` for all of them?

**Comment by awwaiid** [comment]
I like `#!/usr/bin/env perl` more for perlbrew type installs (which are what I use at least)

**Comment by plicease** [comment]
Here is why I prefer `/usr/bin/perl`:

MM and MB convert it to the actual perl used during install.  using `/usr/bin/env perl` leaves it as whatever perl happens to be first in the path.  This can be a problem in environments where you use lots of different versions of Perl (for example perlbrew, etc).

The argument in the other direction is that you might want to use the perl in your path to do your debugging.  But you'd have to make sure that ebug is installed for that Perl as well.  I would argue that `/usr/bin/perl` is more consistent, but it is a small issue and I leave it up to you.

**Comment by plicease** [comment]
An example of how this causes trouble downstream, Debian has a bunch of python scripts installed in /usr/bin that use the /usr/bin/env trick and all of those stop working if I have a different python in the PATH that isn't the system python.  It is really bad when the system tools stop working just because I am using a different version of python or Perl.

I find it easier to install ebug (or whatever) for each Perl that I have and be sure that the prereqs are correctly installed.

**Comment by plicease** [comment]
this is a pretty minor issue though, and would be happy for just consistency either way, thanks for merging the other stuff.

**Comment by awwaiid** [comment]
You had me at "MM and MB convert it to the actual perl used during install" (which I forgot about). I wish this was different :(

**Comment by plicease** [comment]
(I think it is sort of a bug that MM and MB aren't smart enough to convert the `/usr/bin/env perl` too).  Thanks again for taking the time to merge this and keeping me honest by pushing back and asking questions :)

**Pull request merged**
